import { Schema, model } from 'mongoose';

export interface UserDoc {
    username: string;
    passwordHash: string;
    role: 'admin' | 'user';
    streamToken: string;
    streamTokenEnabled: boolean;
    // Stable, unguessable 6-char slug used in this user's per-user playlist filename (<username>.<slug>.m3u).
    // Generated once at creation; never regenerated by compose (so a cron compose keeps the filename stable).
    slug: string;
    allowedPlaylists: string[];
    allowedCustomPlaylists: string[];
    createdAt: Date;
    updatedAt: Date;
}

const UserSchema = new Schema<UserDoc>(
    {
        username: { type: String, required: true, unique: true, lowercase: true, trim: true, index: true },
        passwordHash: { type: String, required: true },
        role: { type: String, required: true, enum: ['admin', 'user'], default: 'user' },
        streamToken: { type: String, required: true, unique: true, index: true },
        streamTokenEnabled: { type: Boolean, required: true, default: true },
        // Sparse + unique: existing users created before this field stay valid (missing) until backfilled,
        // but no two users may ever share a slug (it names their playlist file).
        slug: { type: String, unique: true, sparse: true },
        allowedPlaylists: { type: [String], default: [] },
        allowedCustomPlaylists: { type: [String], default: [] },
    },
    {
        versionKey: false,
        timestamps: true,
    },
);

export const User = model<UserDoc>('User', UserSchema);

// Usernames are used verbatim in per-user playlist FILENAMES (<username>.<slug>.m3u), so restrict them to
// a filesystem-safe charset (lowercase letters, digits, dot, underscore, hyphen). Validate AFTER trimming
// + lowercasing — keeps the on-disk filename identical to what the client builds from the username.
export const USERNAME_RE = /^[a-z0-9._-]+$/;
export function isValidUsername(name: string): boolean {
    return USERNAME_RE.test(name);
}
