// Jesmann EPG catalog — a hardcoded static map of every guide offered at https://epg.jesmann.com/.
// The Jesmann tab in AddEpgSourceModal lets the user pick a Region + Download type; the chosen pair resolves
// to ONE concrete .xml URL that is created as a 'jesmann'-kind XMLTV EPG source (POST /api/epg-sources
// { source: 'jesmann', name, url }). It re-fetches like a 'remote url' source but carries its own type so
// 'remote url' stays reserved for the Custom tab's Remote URL feature. This list is transformed verbatim from the site's
// own `const markets` / `const individualFiles` data (generated offline, not scraped at runtime) so the
// download-type variants offered per region exactly mirror what the site publishes:
//   - markets / continent / full guides → all 6 variants (14d/7d/3d × Standard/IPTV)
//   - Individual Markets (~284 DirecTV city files) → a single 14d Standard variant at the site root
//   - Team Sports → one region with Horizontal / Vertical image variants
//   - Legacy Guides → US/CAN 14d Standard+IPTV, US Locals (OTA) Standard only
// All URLs are plain HTTP GET XMLTV (never .gz). The base origin is JESMANN_BASE.

export const JESMANN_BASE = 'https://epg.jesmann.com';

// The preferred default download type, by id, in order — first one a region actually offers wins.
const DEFAULT_TYPE_ORDER = ['7d-std', '14d-std', '3d-std', '7d-iptv', '14d-iptv', '3d-iptv', 'horizontal', 'vertical'];

export interface JesmannType {
  id: string; // unique within a region
  label: string; // shown in the download-type dropdown
  url: string; // path relative to JESMANN_BASE (always begins with /)
}
export interface JesmannRegion {
  id: string; // globally unique — the region <select> option value
  name: string; // display name
  types: JesmannType[];
}
export interface JesmannGroup {
  group: string; // <optgroup> label
  regions: JesmannRegion[];
}

// The full catalog (~349 regions across 9 groups). Generated offline from the site HTML.
export const JESMANN_CATALOG: JesmannGroup[] = [
  {
    group: "North America",
    regions: [
      { id: "m-canada", name: "Canada", types: [{ id: "14d-std", label: "14d Standard", url: "/Canada.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Canada.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Canada.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Canada.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Canada.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Canada.xml" }] },
      { id: "m-mexico", name: "Mexico", types: [{ id: "14d-std", label: "14d Standard", url: "/Mexico.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Mexico.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Mexico.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Mexico.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Mexico.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Mexico.xml" }] },
      { id: "m-sports", name: "Sports", types: [{ id: "14d-std", label: "14d Standard", url: "/Sports.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Sports.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Sports.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Sports.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Sports.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Sports.xml" }] },
      { id: "m-unitedstates-locals", name: "United States - Locals", types: [{ id: "14d-std", label: "14d Standard", url: "/UnitedStates-Locals.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/UnitedStates-Locals.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/UnitedStates-Locals.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/UnitedStates-Locals.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/UnitedStates-Locals.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/UnitedStates-Locals.xml" }] },
      { id: "m-unitedstates", name: "United States", types: [{ id: "14d-std", label: "14d Standard", url: "/UnitedStates.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/UnitedStates.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/UnitedStates.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/UnitedStates.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/UnitedStates.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/UnitedStates.xml" }] },
      { id: "m-usfast", name: "USFast", types: [{ id: "14d-std", label: "14d Standard", url: "/USFast.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/USFast.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/USFast.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/USFast.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/USFast.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/USFast.xml" }] },
    ],
  },
  {
    group: "Caribbean",
    regions: [
      { id: "m-anguilla", name: "Anguilla", types: [{ id: "14d-std", label: "14d Standard", url: "/Anguilla.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Anguilla.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Anguilla.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Anguilla.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Anguilla.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Anguilla.xml" }] },
      { id: "m-antigua", name: "Antigua", types: [{ id: "14d-std", label: "14d Standard", url: "/Antigua.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Antigua.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Antigua.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Antigua.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Antigua.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Antigua.xml" }] },
      { id: "m-aruba", name: "Aruba", types: [{ id: "14d-std", label: "14d Standard", url: "/Aruba.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Aruba.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Aruba.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Aruba.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Aruba.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Aruba.xml" }] },
      { id: "m-bahamas", name: "Bahamas", types: [{ id: "14d-std", label: "14d Standard", url: "/Bahamas.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Bahamas.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Bahamas.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Bahamas.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Bahamas.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Bahamas.xml" }] },
      { id: "m-barbados", name: "Barbados", types: [{ id: "14d-std", label: "14d Standard", url: "/Barbados.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Barbados.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Barbados.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Barbados.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Barbados.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Barbados.xml" }] },
      { id: "m-bermuda", name: "Bermuda", types: [{ id: "14d-std", label: "14d Standard", url: "/Bermuda.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Bermuda.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Bermuda.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Bermuda.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Bermuda.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Bermuda.xml" }] },
      { id: "m-bonaire", name: "Bonaire", types: [{ id: "14d-std", label: "14d Standard", url: "/Bonaire.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Bonaire.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Bonaire.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Bonaire.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Bonaire.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Bonaire.xml" }] },
      { id: "m-britishvirginislands", name: "British Virgin Islands", types: [{ id: "14d-std", label: "14d Standard", url: "/BritishVirginIslands.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/BritishVirginIslands.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/BritishVirginIslands.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/BritishVirginIslands.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/BritishVirginIslands.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/BritishVirginIslands.xml" }] },
      { id: "m-caymanislands", name: "Cayman Islands", types: [{ id: "14d-std", label: "14d Standard", url: "/CaymanIslands.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/CaymanIslands.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/CaymanIslands.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/CaymanIslands.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/CaymanIslands.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/CaymanIslands.xml" }] },
      { id: "m-curacao", name: "Curacao", types: [{ id: "14d-std", label: "14d Standard", url: "/Curacao.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Curacao.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Curacao.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Curacao.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Curacao.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Curacao.xml" }] },
      { id: "m-dominica", name: "Dominica", types: [{ id: "14d-std", label: "14d Standard", url: "/Dominica.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Dominica.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Dominica.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Dominica.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Dominica.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Dominica.xml" }] },
      { id: "m-dominicanrepublic", name: "Dominican Republic", types: [{ id: "14d-std", label: "14d Standard", url: "/DominicanRepublic.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/DominicanRepublic.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/DominicanRepublic.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/DominicanRepublic.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/DominicanRepublic.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/DominicanRepublic.xml" }] },
      { id: "m-grenada", name: "Grenada", types: [{ id: "14d-std", label: "14d Standard", url: "/Grenada.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Grenada.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Grenada.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Grenada.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Grenada.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Grenada.xml" }] },
      { id: "m-jamaica", name: "Jamaica", types: [{ id: "14d-std", label: "14d Standard", url: "/Jamaica.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Jamaica.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Jamaica.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Jamaica.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Jamaica.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Jamaica.xml" }] },
      { id: "m-saintmartin", name: "Saint Martin", types: [{ id: "14d-std", label: "14d Standard", url: "/SaintMartin.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/SaintMartin.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/SaintMartin.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/SaintMartin.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/SaintMartin.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/SaintMartin.xml" }] },
      { id: "m-saintvincent", name: "Saint Vincent", types: [{ id: "14d-std", label: "14d Standard", url: "/SaintVincent.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/SaintVincent.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/SaintVincent.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/SaintVincent.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/SaintVincent.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/SaintVincent.xml" }] },
      { id: "m-stkitts", name: "St Kitts", types: [{ id: "14d-std", label: "14d Standard", url: "/StKitts.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/StKitts.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/StKitts.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/StKitts.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/StKitts.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/StKitts.xml" }] },
      { id: "m-stlucia", name: "St Lucia", types: [{ id: "14d-std", label: "14d Standard", url: "/StLucia.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/StLucia.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/StLucia.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/StLucia.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/StLucia.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/StLucia.xml" }] },
      { id: "m-trinidad", name: "Trinidad", types: [{ id: "14d-std", label: "14d Standard", url: "/Trinidad.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Trinidad.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Trinidad.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Trinidad.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Trinidad.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Trinidad.xml" }] },
      { id: "m-turks", name: "Turks", types: [{ id: "14d-std", label: "14d Standard", url: "/Turks.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Turks.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Turks.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Turks.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Turks.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Turks.xml" }] },
    ],
  },
  {
    group: "Europe",
    regions: [
      { id: "m-austria", name: "Austria", types: [{ id: "14d-std", label: "14d Standard", url: "/Austria.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Austria.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Austria.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Austria.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Austria.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Austria.xml" }] },
      { id: "m-belgium", name: "Belgium", types: [{ id: "14d-std", label: "14d Standard", url: "/Belgium.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Belgium.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Belgium.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Belgium.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Belgium.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Belgium.xml" }] },
      { id: "m-denmark", name: "Denmark", types: [{ id: "14d-std", label: "14d Standard", url: "/Denmark.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Denmark.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Denmark.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Denmark.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Denmark.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Denmark.xml" }] },
      { id: "m-finland", name: "Finland", types: [{ id: "14d-std", label: "14d Standard", url: "/Finland.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Finland.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Finland.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Finland.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Finland.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Finland.xml" }] },
      { id: "m-france", name: "France", types: [{ id: "14d-std", label: "14d Standard", url: "/France.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/France.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/France.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/France.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/France.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/France.xml" }] },
      { id: "m-germany", name: "Germany", types: [{ id: "14d-std", label: "14d Standard", url: "/Germany.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Germany.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Germany.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Germany.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Germany.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Germany.xml" }] },
      { id: "m-ireland", name: "Ireland", types: [{ id: "14d-std", label: "14d Standard", url: "/Ireland.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Ireland.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Ireland.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Ireland.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Ireland.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Ireland.xml" }] },
      { id: "m-italy", name: "Italy", types: [{ id: "14d-std", label: "14d Standard", url: "/Italy.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Italy.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Italy.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Italy.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Italy.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Italy.xml" }] },
      { id: "m-netherlands", name: "Netherlands", types: [{ id: "14d-std", label: "14d Standard", url: "/Netherlands.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Netherlands.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Netherlands.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Netherlands.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Netherlands.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Netherlands.xml" }] },
      { id: "m-norway", name: "Norway", types: [{ id: "14d-std", label: "14d Standard", url: "/Norway.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Norway.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Norway.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Norway.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Norway.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Norway.xml" }] },
      { id: "m-poland", name: "Poland", types: [{ id: "14d-std", label: "14d Standard", url: "/Poland.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Poland.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Poland.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Poland.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Poland.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Poland.xml" }] },
      { id: "m-spain", name: "Spain", types: [{ id: "14d-std", label: "14d Standard", url: "/Spain.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Spain.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Spain.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Spain.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Spain.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Spain.xml" }] },
      { id: "m-sweden", name: "Sweden", types: [{ id: "14d-std", label: "14d Standard", url: "/Sweden.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Sweden.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Sweden.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Sweden.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Sweden.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Sweden.xml" }] },
      { id: "m-switzerland", name: "Switzerland", types: [{ id: "14d-std", label: "14d Standard", url: "/Switzerland.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Switzerland.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Switzerland.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Switzerland.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Switzerland.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Switzerland.xml" }] },
      { id: "m-unitedkingdom", name: "United Kingdom", types: [{ id: "14d-std", label: "14d Standard", url: "/UnitedKingdom.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/UnitedKingdom.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/UnitedKingdom.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/UnitedKingdom.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/UnitedKingdom.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/UnitedKingdom.xml" }] },
    ],
  },
  {
    group: "Latin & South America",
    regions: [
      { id: "m-argentina", name: "Argentina", types: [{ id: "14d-std", label: "14d Standard", url: "/Argentina.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Argentina.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Argentina.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Argentina.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Argentina.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Argentina.xml" }] },
      { id: "m-belize", name: "Belize", types: [{ id: "14d-std", label: "14d Standard", url: "/Belize.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Belize.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Belize.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Belize.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Belize.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Belize.xml" }] },
      { id: "m-brazil", name: "Brazil", types: [{ id: "14d-std", label: "14d Standard", url: "/Brazil.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Brazil.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Brazil.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Brazil.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Brazil.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Brazil.xml" }] },
      { id: "m-chile", name: "Chile", types: [{ id: "14d-std", label: "14d Standard", url: "/Chile.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Chile.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Chile.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Chile.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Chile.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Chile.xml" }] },
      { id: "m-colombia", name: "Colombia", types: [{ id: "14d-std", label: "14d Standard", url: "/Colombia.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Colombia.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Colombia.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Colombia.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Colombia.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Colombia.xml" }] },
      { id: "m-costarica", name: "Costa Rica", types: [{ id: "14d-std", label: "14d Standard", url: "/CostaRica.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/CostaRica.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/CostaRica.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/CostaRica.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/CostaRica.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/CostaRica.xml" }] },
      { id: "m-ecuador", name: "Ecuador", types: [{ id: "14d-std", label: "14d Standard", url: "/Ecuador.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Ecuador.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Ecuador.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Ecuador.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Ecuador.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Ecuador.xml" }] },
      { id: "m-guatemala", name: "Guatemala", types: [{ id: "14d-std", label: "14d Standard", url: "/Guatemala.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Guatemala.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Guatemala.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Guatemala.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Guatemala.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Guatemala.xml" }] },
      { id: "m-guyana", name: "Guyana", types: [{ id: "14d-std", label: "14d Standard", url: "/Guyana.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Guyana.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Guyana.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Guyana.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Guyana.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Guyana.xml" }] },
      { id: "m-honduras", name: "Honduras", types: [{ id: "14d-std", label: "14d Standard", url: "/Honduras.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Honduras.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Honduras.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Honduras.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Honduras.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Honduras.xml" }] },
      { id: "m-panama", name: "Panama", types: [{ id: "14d-std", label: "14d Standard", url: "/Panama.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Panama.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Panama.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Panama.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Panama.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Panama.xml" }] },
      { id: "m-peru", name: "Peru", types: [{ id: "14d-std", label: "14d Standard", url: "/Peru.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Peru.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Peru.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Peru.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Peru.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Peru.xml" }] },
      { id: "m-uruguay", name: "Uruguay", types: [{ id: "14d-std", label: "14d Standard", url: "/Uruguay.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Uruguay.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Uruguay.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Uruguay.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Uruguay.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Uruguay.xml" }] },
      { id: "m-venezuela", name: "Venezuela", types: [{ id: "14d-std", label: "14d Standard", url: "/Venezuela.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Venezuela.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Venezuela.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Venezuela.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Venezuela.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Venezuela.xml" }] },
    ],
  },
  {
    group: "Oceania",
    regions: [
      { id: "m-australia", name: "Australia", types: [{ id: "14d-std", label: "14d Standard", url: "/Australia.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Australia.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Australia.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Australia.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Australia.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Australia.xml" }] },
    ],
  },
  {
    group: "Continent & Full Guides",
    regions: [
      { id: "m-caribbean", name: "Caribbean", types: [{ id: "14d-std", label: "14d Standard", url: "/Caribbean.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Caribbean.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Caribbean.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Caribbean.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Caribbean.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Caribbean.xml" }] },
      { id: "m-europe", name: "Europe", types: [{ id: "14d-std", label: "14d Standard", url: "/Europe.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Europe.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/Europe.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/Europe.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/Europe.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/Europe.xml" }] },
      { id: "m-fullguide", name: "Full Guide", types: [{ id: "14d-std", label: "14d Standard", url: "/FullGuide.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/FullGuide.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/FullGuide.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/FullGuide.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/FullGuide.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/FullGuide.xml" }] },
      { id: "m-latinsouthamerica", name: "Latin South America", types: [{ id: "14d-std", label: "14d Standard", url: "/LatinSouthAmerica.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/LatinSouthAmerica.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/LatinSouthAmerica.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/LatinSouthAmerica.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/LatinSouthAmerica.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/LatinSouthAmerica.xml" }] },
      { id: "m-northamerica", name: "North America", types: [{ id: "14d-std", label: "14d Standard", url: "/NorthAmerica.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/NorthAmerica.xml" }, { id: "7d-std", label: "7d Standard", url: "/7daygracenote/NorthAmerica.xml" }, { id: "7d-iptv", label: "7d IPTV", url: "/7dayiptv/NorthAmerica.xml" }, { id: "3d-std", label: "3d Standard", url: "/3daygracenote/NorthAmerica.xml" }, { id: "3d-iptv", label: "3d IPTV", url: "/3dayiptv/NorthAmerica.xml" }] },
    ],
  },
  {
    group: "Team Sports",
    regions: [
      { id: "teamsports", name: "Team Sports", types: [{ id: "horizontal", label: "Horizontal Images", url: "/TeamSports/TeamSports-horizontal.xml" }, { id: "vertical", label: "Vertical Images", url: "/TeamSports/TeamSports-vertical.xml" }] },
    ],
  },
  {
    group: "Legacy Guides",
    regions: [
      { id: "legacy-us", name: "United States (Legacy)", types: [{ id: "14d-std", label: "14d Standard", url: "/UnitedStates-og.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/UnitedStates-og.xml" }] },
      { id: "legacy-can", name: "Canada (Legacy)", types: [{ id: "14d-std", label: "14d Standard", url: "/Canada-og.xml" }, { id: "14d-iptv", label: "14d IPTV", url: "/iptv/Canada-og.xml" }] },
      { id: "legacy-ota", name: "US Locals (OTA)", types: [{ id: "14d-std", label: "14d Standard", url: "/UnitedStates-Locals-og.xml" }] },
    ],
  },
  {
    group: "Individual Markets",
    regions: [
      { id: "ind-abilenetx-xml", name: "Abilene TX", types: [{ id: "14d-std", label: "14d Standard", url: "/AbileneTX.xml" }] },
      { id: "ind-albanyga-xml", name: "Albany GA", types: [{ id: "14d-std", label: "14d Standard", url: "/AlbanyGA.xml" }] },
      { id: "ind-albanyny-xml", name: "Albany NY", types: [{ id: "14d-std", label: "14d Standard", url: "/AlbanyNY.xml" }] },
      { id: "ind-albuquerquenm-xml", name: "Albuquerque NM", types: [{ id: "14d-std", label: "14d Standard", url: "/AlbuquerqueNM.xml" }] },
      { id: "ind-alexandriala-xml", name: "Alexandria LA", types: [{ id: "14d-std", label: "14d Standard", url: "/AlexandriaLA.xml" }] },
      { id: "ind-alpenami-dish-xml", name: "Alpena MI-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/AlpenaMI-Dish.xml" }] },
      { id: "ind-amarillotx-xml", name: "Amarillo TX", types: [{ id: "14d-std", label: "14d Standard", url: "/AmarilloTX.xml" }] },
      { id: "ind-anchorageak-ota-xml", name: "Anchorage AK-OTA", types: [{ id: "14d-std", label: "14d Standard", url: "/AnchorageAK-OTA.xml" }] },
      { id: "ind-anchorageak-xml", name: "Anchorage AK", types: [{ id: "14d-std", label: "14d Standard", url: "/AnchorageAK.xml" }] },
      { id: "ind-atlantaga-spectrum-xml", name: "Atlanta GA-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/AtlantaGA-Spectrum.xml" }] },
      { id: "ind-atlantaga-xml", name: "Atlanta GA", types: [{ id: "14d-std", label: "14d Standard", url: "/AtlantaGA.xml" }] },
      { id: "ind-atlanticia-mediacom-xml", name: "Atlantic IA-Mediacom", types: [{ id: "14d-std", label: "14d Standard", url: "/AtlanticIA-Mediacom.xml" }] },
      { id: "ind-augustaga-xml", name: "Augusta GA", types: [{ id: "14d-std", label: "14d Standard", url: "/AugustaGA.xml" }] },
      { id: "ind-austintx-xml", name: "Austin TX", types: [{ id: "14d-std", label: "14d Standard", url: "/AustinTX.xml" }] },
      { id: "ind-bakersfieldca-xml", name: "Bakersfield CA", types: [{ id: "14d-std", label: "14d Standard", url: "/BakersfieldCA.xml" }] },
      { id: "ind-baltimoremd-mediacom-xml", name: "Baltimore MD-Mediacom", types: [{ id: "14d-std", label: "14d Standard", url: "/BaltimoreMD-Mediacom.xml" }] },
      { id: "ind-baltimoremd-xml", name: "Baltimore MD", types: [{ id: "14d-std", label: "14d Standard", url: "/BaltimoreMD.xml" }] },
      { id: "ind-bangorme-xml", name: "Bangor ME", types: [{ id: "14d-std", label: "14d Standard", url: "/BangorME.xml" }] },
      { id: "ind-batonrougela-xml", name: "Baton Rouge LA", types: [{ id: "14d-std", label: "14d Standard", url: "/BatonRougeLA.xml" }] },
      { id: "ind-beaumonttx-xml", name: "Beaumont TX", types: [{ id: "14d-std", label: "14d Standard", url: "/BeaumontTX.xml" }] },
      { id: "ind-bendor-tds-xml", name: "Bend OR-TDS", types: [{ id: "14d-std", label: "14d Standard", url: "/BendOR-TDS.xml" }] },
      { id: "ind-bendor-xml", name: "Bend OR", types: [{ id: "14d-std", label: "14d Standard", url: "/BendOR.xml" }] },
      { id: "ind-billingsmt-spectrum-xml", name: "Billings MT-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/BillingsMT-Spectrum.xml" }] },
      { id: "ind-billingsmt-xml", name: "Billings MT", types: [{ id: "14d-std", label: "14d Standard", url: "/BillingsMT.xml" }] },
      { id: "ind-biloxims-xml", name: "Biloxi MS", types: [{ id: "14d-std", label: "14d Standard", url: "/BiloxiMS.xml" }] },
      { id: "ind-binghamtonny-xml", name: "Binghamton NY", types: [{ id: "14d-std", label: "14d Standard", url: "/BinghamtonNY.xml" }] },
      { id: "ind-birminghamal-xml", name: "Birmingham AL", types: [{ id: "14d-std", label: "14d Standard", url: "/BirminghamAL.xml" }] },
      { id: "ind-bloomingtonil-xfinity-xml", name: "Bloomington IL-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/BloomingtonIL-Xfinity.xml" }] },
      { id: "ind-bluefieldwv-xml", name: "Bluefield WV", types: [{ id: "14d-std", label: "14d Standard", url: "/BluefieldWV.xml" }] },
      { id: "ind-boiseid-xml", name: "Boise ID", types: [{ id: "14d-std", label: "14d Standard", url: "/BoiseID.xml" }] },
      { id: "ind-bostonma-xfinity-xml", name: "Boston MA-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/BostonMA-Xfinity.xml" }] },
      { id: "ind-bostonma-xml", name: "Boston MA", types: [{ id: "14d-std", label: "14d Standard", url: "/BostonMA.xml" }] },
      { id: "ind-bowlinggreenky-dish-xml", name: "Bowling Green KY-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/BowlingGreenKY-Dish.xml" }] },
      { id: "ind-buffalony-spectrum-xml", name: "Buffalo NY-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/BuffaloNY-Spectrum.xml" }] },
      { id: "ind-buffalony-xml", name: "Buffalo NY", types: [{ id: "14d-std", label: "14d Standard", url: "/BuffaloNY.xml" }] },
      { id: "ind-burlingtonvt-xml", name: "Burlington VT", types: [{ id: "14d-std", label: "14d Standard", url: "/BurlingtonVT.xml" }] },
      { id: "ind-buttemt-tdstv-xml", name: "Butte MT-TDSTV", types: [{ id: "14d-std", label: "14d Standard", url: "/ButteMT-TDSTV.xml" }] },
      { id: "ind-buttemt-xml", name: "Butte MT", types: [{ id: "14d-std", label: "14d Standard", url: "/ButteMT.xml" }] },
      { id: "ind-cadillacmi-spectrum-xml", name: "Cadillac MI-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/CadillacMI-Spectrum.xml" }] },
      { id: "ind-canada-bell-xml", name: "Canada-Bell", types: [{ id: "14d-std", label: "14d Standard", url: "/Canada-Bell.xml" }] },
      { id: "ind-canada-shaw-xml", name: "Canada-Shaw", types: [{ id: "14d-std", label: "14d Standard", url: "/Canada-Shaw.xml" }] },
      { id: "ind-capegirardeaumo-spectrum-xml", name: "Cape Girardeau MO-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/CapeGirardeauMO-Spectrum.xml" }] },
      { id: "ind-casperwy-dish-xml", name: "Casper WY-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/CasperWY-Dish.xml" }] },
      { id: "ind-cedarrapidsia-xml", name: "Cedar Rapids IA", types: [{ id: "14d-std", label: "14d Standard", url: "/CedarRapidsIA.xml" }] },
      { id: "ind-champaignil-xml", name: "Champaign IL", types: [{ id: "14d-std", label: "14d Standard", url: "/ChampaignIL.xml" }] },
      { id: "ind-charleston-huntingtonwv-xml", name: "Charleston-Huntington WV", types: [{ id: "14d-std", label: "14d Standard", url: "/Charleston-HuntingtonWV.xml" }] },
      { id: "ind-charlestonsc-xml", name: "Charleston SC", types: [{ id: "14d-std", label: "14d Standard", url: "/CharlestonSC.xml" }] },
      { id: "ind-charlottenc-xml", name: "Charlotte NC", types: [{ id: "14d-std", label: "14d Standard", url: "/CharlotteNC.xml" }] },
      { id: "ind-charlottesvilleva-xml", name: "Charlottesville VA", types: [{ id: "14d-std", label: "14d Standard", url: "/CharlottesvilleVA.xml" }] },
      { id: "ind-chattanoogatn-xml", name: "Chattanooga TN", types: [{ id: "14d-std", label: "14d Standard", url: "/ChattanoogaTN.xml" }] },
      { id: "ind-cheyennewy-dish-xml", name: "Cheyenne WY-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/CheyenneWY-Dish.xml" }] },
      { id: "ind-chicagoil-xfinity-xml", name: "Chicago IL-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/ChicagoIL-Xfinity.xml" }] },
      { id: "ind-chicagoil-xml", name: "Chicago IL", types: [{ id: "14d-std", label: "14d Standard", url: "/ChicagoIL.xml" }] },
      { id: "ind-chico-reddingca-xml", name: "Chico-Redding CA", types: [{ id: "14d-std", label: "14d Standard", url: "/Chico-ReddingCA.xml" }] },
      { id: "ind-cincinnatioh-xml", name: "Cincinnati OH", types: [{ id: "14d-std", label: "14d Standard", url: "/CincinnatiOH.xml" }] },
      { id: "ind-clarksburgtn-xml", name: "Clarksburg TN", types: [{ id: "14d-std", label: "14d Standard", url: "/ClarksburgTN.xml" }] },
      { id: "ind-clevelandoh-xml", name: "Cleveland OH", types: [{ id: "14d-std", label: "14d Standard", url: "/ClevelandOH.xml" }] },
      { id: "ind-clintonil-ota-xml", name: "Clinton IL-OTA", types: [{ id: "14d-std", label: "14d Standard", url: "/ClintonIL-OTA.xml" }] },
      { id: "ind-coloradospringsco-xml", name: "Colorado Springs CO", types: [{ id: "14d-std", label: "14d Standard", url: "/ColoradoSpringsCO.xml" }] },
      { id: "ind-columbia-jeffersoncitymo-xml", name: "Columbia-Jefferson City MO", types: [{ id: "14d-std", label: "14d Standard", url: "/Columbia-JeffersonCityMO.xml" }] },
      { id: "ind-columbiasc-dish-xml", name: "Columbia SC-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/ColumbiaSC-Dish.xml" }] },
      { id: "ind-columbiasc-xml", name: "Columbia SC", types: [{ id: "14d-std", label: "14d Standard", url: "/ColumbiaSC.xml" }] },
      { id: "ind-columbusga-xml", name: "Columbus GA", types: [{ id: "14d-std", label: "14d Standard", url: "/ColumbusGA.xml" }] },
      { id: "ind-columbusoh-xml", name: "Columbus OH", types: [{ id: "14d-std", label: "14d Standard", url: "/ColumbusOH.xml" }] },
      { id: "ind-columbus-tupeloms-xml", name: "Columbus-Tupelo MS", types: [{ id: "14d-std", label: "14d Standard", url: "/Columbus-TupeloMS.xml" }] },
      { id: "ind-corpuschristitx-xml", name: "Corpus Christi TX", types: [{ id: "14d-std", label: "14d Standard", url: "/CorpusChristiTX.xml" }] },
      { id: "ind-dallastx-uverse-xml", name: "Dallas TX-Uverse", types: [{ id: "14d-std", label: "14d Standard", url: "/DallasTX-Uverse.xml" }] },
      { id: "ind-dallastx-xml", name: "Dallas TX", types: [{ id: "14d-std", label: "14d Standard", url: "/DallasTX.xml" }] },
      { id: "ind-davenportia-xml", name: "Davenport IA", types: [{ id: "14d-std", label: "14d Standard", url: "/DavenportIA.xml" }] },
      { id: "ind-davenportil-xfinity-xml", name: "Davenport IL-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/DavenportIL-Xfinity.xml" }] },
      { id: "ind-daytonoh-xml", name: "Dayton OH", types: [{ id: "14d-std", label: "14d Standard", url: "/DaytonOH.xml" }] },
      { id: "ind-denverco-xfinity-xml", name: "Denver CO-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/DenverCO-Xfinity.xml" }] },
      { id: "ind-denverco-xml", name: "Denver CO", types: [{ id: "14d-std", label: "14d Standard", url: "/DenverCO.xml" }] },
      { id: "ind-deserthillsaz-optimum-xml", name: "Desert Hills AZ-Optimum", types: [{ id: "14d-std", label: "14d Standard", url: "/DesertHillsAZ-Optimum.xml" }] },
      { id: "ind-desmoinesia-xml", name: "Des Moines IA", types: [{ id: "14d-std", label: "14d Standard", url: "/DesMoinesIA.xml" }] },
      { id: "ind-detroitmi-xml", name: "Detroit MI", types: [{ id: "14d-std", label: "14d Standard", url: "/DetroitMI.xml" }] },
      { id: "ind-dothanal-xml", name: "Dothan AL", types: [{ id: "14d-std", label: "14d Standard", url: "/DothanAL.xml" }] },
      { id: "ind-duluthmn-xml", name: "Duluth MN", types: [{ id: "14d-std", label: "14d Standard", url: "/DuluthMN.xml" }] },
      { id: "ind-echolakepa-privatel-xml", name: "Echo Lake PA-Privatel", types: [{ id: "14d-std", label: "14d Standard", url: "/EchoLakePA-Privatel.xml" }] },
      { id: "ind-eldoradoar-optimum-xml", name: "El Dorado AR-Optimum", types: [{ id: "14d-std", label: "14d Standard", url: "/ElDoradoAR-Optimum.xml" }] },
      { id: "ind-elmirany-xml", name: "Elmira NY", types: [{ id: "14d-std", label: "14d Standard", url: "/ElmiraNY.xml" }] },
      { id: "ind-elpasotx-xml", name: "El Paso TX", types: [{ id: "14d-std", label: "14d Standard", url: "/ElPasoTX.xml" }] },
      { id: "ind-eriepa-xml", name: "Erie PA", types: [{ id: "14d-std", label: "14d Standard", url: "/EriePA.xml" }] },
      { id: "ind-eugeneor-dish-xml", name: "Eugene OR-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/EugeneOR-Dish.xml" }] },
      { id: "ind-eugeneor-xml", name: "Eugene OR", types: [{ id: "14d-std", label: "14d Standard", url: "/EugeneOR.xml" }] },
      { id: "ind-eurekaca-xml", name: "Eureka CA", types: [{ id: "14d-std", label: "14d Standard", url: "/EurekaCA.xml" }] },
      { id: "ind-evansvillein-spectrum-xml", name: "Evansville IN-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/EvansvilleIN-Spectrum.xml" }] },
      { id: "ind-evansvillein-xml", name: "Evansville IN", types: [{ id: "14d-std", label: "14d Standard", url: "/EvansvilleIN.xml" }] },
      { id: "ind-fairbanksak-xml", name: "Fairbanks AK", types: [{ id: "14d-std", label: "14d Standard", url: "/FairbanksAK.xml" }] },
      { id: "ind-fargond-xml", name: "Fargo ND", types: [{ id: "14d-std", label: "14d Standard", url: "/FargoND.xml" }] },
      { id: "ind-farmingtonmo-spectrum-xml", name: "Farmington MO-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/FarmingtonMO-Spectrum.xml" }] },
      { id: "ind-flint-saginawmi-xml", name: "Flint-Saginaw MI", types: [{ id: "14d-std", label: "14d Standard", url: "/Flint-SaginawMI.xml" }] },
      { id: "ind-fortmeyersfl-dish-xml", name: "Fort Meyers FL-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/FortMeyersFL-Dish.xml" }] },
      { id: "ind-fortwaynein-xml", name: "Fort Wayne IN", types: [{ id: "14d-std", label: "14d Standard", url: "/FortWayneIN.xml" }] },
      { id: "ind-fresnoca-xml", name: "Fresno CA", types: [{ id: "14d-std", label: "14d Standard", url: "/FresnoCA.xml" }] },
      { id: "ind-ftmyers-naplesfl-xml", name: "Ft Myers-Naples FL", types: [{ id: "14d-std", label: "14d Standard", url: "/FtMyers-NaplesFL.xml" }] },
      { id: "ind-ftsmithar-xml", name: "Ft Smith AR", types: [{ id: "14d-std", label: "14d Standard", url: "/FtSmithAR.xml" }] },
      { id: "ind-gainesvillefl-xml", name: "Gainesville FL", types: [{ id: "14d-std", label: "14d Standard", url: "/GainesvilleFL.xml" }] },
      { id: "ind-glendivesd-dish-xml", name: "Glendive SD-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/GlendiveSD-Dish.xml" }] },
      { id: "ind-grandjunctionco-dish-xml", name: "Grand Junction CO-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/GrandJunctionCO-Dish.xml" }] },
      { id: "ind-grandrapidsmi-xml", name: "Grand Rapids MI", types: [{ id: "14d-std", label: "14d Standard", url: "/GrandRapidsMI.xml" }] },
      { id: "ind-greatfallsmt-xml", name: "Great Falls MT", types: [{ id: "14d-std", label: "14d Standard", url: "/GreatFallsMT.xml" }] },
      { id: "ind-greenbaywi-xml", name: "Green Bay WI", types: [{ id: "14d-std", label: "14d Standard", url: "/GreenBayWI.xml" }] },
      { id: "ind-greensboronc-xml", name: "Greensboro NC", types: [{ id: "14d-std", label: "14d Standard", url: "/GreensboroNC.xml" }] },
      { id: "ind-greenville-newbernnc-xml", name: "Greenville-New Bern NC", types: [{ id: "14d-std", label: "14d Standard", url: "/Greenville-NewBernNC.xml" }] },
      { id: "ind-greenvillesc-xml", name: "Greenville SC", types: [{ id: "14d-std", label: "14d Standard", url: "/GreenvilleSC.xml" }] },
      { id: "ind-greenwood-greenvillems-xml", name: "Greenwood-Greenville MS", types: [{ id: "14d-std", label: "14d Standard", url: "/Greenwood-GreenvilleMS.xml" }] },
      { id: "ind-hammondla-spectrum-xml", name: "Hammond LA-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/HammondLA-Spectrum.xml" }] },
      { id: "ind-harlingentx-xml", name: "Harlingen TX", types: [{ id: "14d-std", label: "14d Standard", url: "/HarlingenTX.xml" }] },
      { id: "ind-harrisburgpa-xml", name: "Harrisburg PA", types: [{ id: "14d-std", label: "14d Standard", url: "/HarrisburgPA.xml" }] },
      { id: "ind-harrisonburgva-xml", name: "Harrisonburg VA", types: [{ id: "14d-std", label: "14d Standard", url: "/HarrisonburgVA.xml" }] },
      { id: "ind-hartford-newhavenct-xml", name: "Hartford-New Haven CT", types: [{ id: "14d-std", label: "14d Standard", url: "/Hartford-NewHavenCT.xml" }] },
      { id: "ind-hastingsne-allo-xml", name: "Hastings NE-Allo", types: [{ id: "14d-std", label: "14d Standard", url: "/HastingsNE-Allo.xml" }] },
      { id: "ind-hattiesburg-laurelms-xml", name: "Hattiesburg-Laurel MS", types: [{ id: "14d-std", label: "14d Standard", url: "/Hattiesburg-LaurelMS.xml" }] },
      { id: "ind-hazardky-spectrum-xml", name: "Hazard KY-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/HazardKY-Spectrum.xml" }] },
      { id: "ind-helenamt-dish-xml", name: "Helena MT-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/HelenaMT-Dish.xml" }] },
      { id: "ind-honoluluhi-spectrum-xml", name: "Honolulu HI-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/HonoluluHI-Spectrum.xml" }] },
      { id: "ind-honoluluhi-xml", name: "Honolulu HI", types: [{ id: "14d-std", label: "14d Standard", url: "/HonoluluHI.xml" }] },
      { id: "ind-houstontx-xml", name: "Houston TX", types: [{ id: "14d-std", label: "14d Standard", url: "/HoustonTX.xml" }] },
      { id: "ind-huntsvilleal-xml", name: "Huntsville AL", types: [{ id: "14d-std", label: "14d Standard", url: "/HuntsvilleAL.xml" }] },
      { id: "ind-idahofalls-pocatelloid-xml", name: "Idaho Falls-Pocatello ID", types: [{ id: "14d-std", label: "14d Standard", url: "/IdahoFalls-PocatelloID.xml" }] },
      { id: "ind-indianapolisin-xfinity-xml", name: "Indianapolis IN-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/IndianapolisIN-Xfinity.xml" }] },
      { id: "ind-indianapolisin-xml", name: "Indianapolis IN", types: [{ id: "14d-std", label: "14d Standard", url: "/IndianapolisIN.xml" }] },
      { id: "ind-jacksonms-xml", name: "Jackson MS", types: [{ id: "14d-std", label: "14d Standard", url: "/JacksonMS.xml" }] },
      { id: "ind-jacksontn-xml", name: "Jackson TN", types: [{ id: "14d-std", label: "14d Standard", url: "/JacksonTN.xml" }] },
      { id: "ind-jacksonvillefl-xml", name: "Jacksonville FL", types: [{ id: "14d-std", label: "14d Standard", url: "/JacksonvilleFL.xml" }] },
      { id: "ind-jeffersoncitymo-mediacom-xml", name: "Jefferson City MO-Mediacom", types: [{ id: "14d-std", label: "14d Standard", url: "/JeffersonCityMO-Mediacom.xml" }] },
      { id: "ind-johnstownpa-xml", name: "Johnstown PA", types: [{ id: "14d-std", label: "14d Standard", url: "/JohnstownPA.xml" }] },
      { id: "ind-jonesboroar-xml", name: "Jonesboro AR", types: [{ id: "14d-std", label: "14d Standard", url: "/JonesboroAR.xml" }] },
      { id: "ind-joplinmo-mediacom-xml", name: "Joplin MO-Mediacom", types: [{ id: "14d-std", label: "14d Standard", url: "/JoplinMO-Mediacom.xml" }] },
      { id: "ind-joplinmo-pittsburgks-xml", name: "Joplin MO-Pittsburg KS", types: [{ id: "14d-std", label: "14d Standard", url: "/JoplinMO-PittsburgKS.xml" }] },
      { id: "ind-juneauak-xml", name: "Juneau AK", types: [{ id: "14d-std", label: "14d Standard", url: "/JuneauAK.xml" }] },
      { id: "ind-kansascitymo-spectrum-xml", name: "Kansas City MO-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/KansasCityMO-Spectrum.xml" }] },
      { id: "ind-kansascitymo-xml", name: "Kansas City MO", types: [{ id: "14d-std", label: "14d Standard", url: "/KansasCityMO.xml" }] },
      { id: "ind-kirksvillemo-sparklight-xml", name: "Kirksville MO-Sparklight", types: [{ id: "14d-std", label: "14d Standard", url: "/KirksvilleMO-Sparklight.xml" }] },
      { id: "ind-knoxvilletn-xml", name: "Knoxville TN", types: [{ id: "14d-std", label: "14d Standard", url: "/KnoxvilleTN.xml" }] },
      { id: "ind-lacrosse-eauclairewi-xml", name: "La Crosse-Eau Claire WI", types: [{ id: "14d-std", label: "14d Standard", url: "/LaCrosse-EauClaireWI.xml" }] },
      { id: "ind-lafayettein-xml", name: "Lafayette IN", types: [{ id: "14d-std", label: "14d Standard", url: "/LafayetteIN.xml" }] },
      { id: "ind-lafayettela-xfinity-xml", name: "Lafayette LA-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/LafayetteLA-Xfinity.xml" }] },
      { id: "ind-lafayettela-xml", name: "Lafayette LA", types: [{ id: "14d-std", label: "14d Standard", url: "/LafayetteLA.xml" }] },
      { id: "ind-lakecharlesla-xml", name: "Lake Charles LA", types: [{ id: "14d-std", label: "14d Standard", url: "/LakeCharlesLA.xml" }] },
      { id: "ind-lansingmi-wow-xml", name: "Lansing MI-WOW", types: [{ id: "14d-std", label: "14d Standard", url: "/LansingMI-WOW.xml" }] },
      { id: "ind-lansingmi-xml", name: "Lansing MI", types: [{ id: "14d-std", label: "14d Standard", url: "/LansingMI.xml" }] },
      { id: "ind-laredotx-spectrum-xml", name: "Laredo TX-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/LaredoTX-Spectrum.xml" }] },
      { id: "ind-laredotx-xml", name: "Laredo TX", types: [{ id: "14d-std", label: "14d Standard", url: "/LaredoTX.xml" }] },
      { id: "ind-lasvegasnv-cox-xml", name: "Las Vegas NV-Cox", types: [{ id: "14d-std", label: "14d Standard", url: "/LasVegasNV-Cox.xml" }] },
      { id: "ind-lasvegasnv-xml", name: "Las Vegas NV", types: [{ id: "14d-std", label: "14d Standard", url: "/LasVegasNV.xml" }] },
      { id: "ind-lawtonok-ozarksgo-xml", name: "Lawton OK-Ozarks Go", types: [{ id: "14d-std", label: "14d Standard", url: "/LawtonOK-OzarksGo.xml" }] },
      { id: "ind-lexingtonky-xml", name: "Lexington KY", types: [{ id: "14d-std", label: "14d Standard", url: "/LexingtonKY.xml" }] },
      { id: "ind-limaoh-xml", name: "Lima OH", types: [{ id: "14d-std", label: "14d Standard", url: "/LimaOH.xml" }] },
      { id: "ind-lincoln-hastingsne-xml", name: "Lincoln-Hastings NE", types: [{ id: "14d-std", label: "14d Standard", url: "/Lincoln-HastingsNE.xml" }] },
      { id: "ind-littlerockar-xml", name: "Little Rock AR", types: [{ id: "14d-std", label: "14d Standard", url: "/LittleRockAR.xml" }] },
      { id: "ind-losangelesca-dish-xml", name: "Los Angeles CA-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/LosAngelesCA-Dish.xml" }] },
      { id: "ind-losangelesca-xml", name: "Los Angeles CA", types: [{ id: "14d-std", label: "14d Standard", url: "/LosAngelesCA.xml" }] },
      { id: "ind-louisvilleky-xml", name: "Louisville KY", types: [{ id: "14d-std", label: "14d Standard", url: "/LouisvilleKY.xml" }] },
      { id: "ind-lubbocktx-dish-xml", name: "Lubbock TX-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/LubbockTX-Dish.xml" }] },
      { id: "ind-lubbocktx-xml", name: "Lubbock TX", types: [{ id: "14d-std", label: "14d Standard", url: "/LubbockTX.xml" }] },
      { id: "ind-maconga-xml", name: "Macon GA", types: [{ id: "14d-std", label: "14d Standard", url: "/MaconGA.xml" }] },
      { id: "ind-madisonwi-xml", name: "Madison WI", types: [{ id: "14d-std", label: "14d Standard", url: "/MadisonWI.xml" }] },
      { id: "ind-madridia-mediacom-xml", name: "Madrid IA-Mediacom", types: [{ id: "14d-std", label: "14d Standard", url: "/MadridIA-Mediacom.xml" }] },
      { id: "ind-mankatomn-xml", name: "Mankato MN", types: [{ id: "14d-std", label: "14d Standard", url: "/MankatoMN.xml" }] },
      { id: "ind-marquettemi-xml", name: "Marquette MI", types: [{ id: "14d-std", label: "14d Standard", url: "/MarquetteMI.xml" }] },
      { id: "ind-medfordor-xml", name: "Medford OR", types: [{ id: "14d-std", label: "14d Standard", url: "/MedfordOR.xml" }] },
      { id: "ind-memphistn-uverse-xml", name: "Memphis TN-Uverse", types: [{ id: "14d-std", label: "14d Standard", url: "/MemphisTN-Uverse.xml" }] },
      { id: "ind-memphistn-xml", name: "Memphis TN", types: [{ id: "14d-std", label: "14d Standard", url: "/MemphisTN.xml" }] },
      { id: "ind-meridianms-xml", name: "Meridian MS", types: [{ id: "14d-std", label: "14d Standard", url: "/MeridianMS.xml" }] },
      { id: "ind-miamifl-xfinity-xml", name: "Miami FL-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/MiamiFL-Xfinity.xml" }] },
      { id: "ind-miamifl-xml", name: "Miami FL", types: [{ id: "14d-std", label: "14d Standard", url: "/MiamiFL.xml" }] },
      { id: "ind-milwaukeewi-xml", name: "Milwaukee WI", types: [{ id: "14d-std", label: "14d Standard", url: "/MilwaukeeWI.xml" }] },
      { id: "ind-minneapolismn-xml", name: "Minneapolis MN", types: [{ id: "14d-std", label: "14d Standard", url: "/MinneapolisMN.xml" }] },
      { id: "ind-minotnd-xml", name: "Minot ND", types: [{ id: "14d-std", label: "14d Standard", url: "/MinotND.xml" }] },
      { id: "ind-missoulamt-xml", name: "Missoula MT", types: [{ id: "14d-std", label: "14d Standard", url: "/MissoulaMT.xml" }] },
      { id: "ind-mobileal-xml", name: "Mobile AL", types: [{ id: "14d-std", label: "14d Standard", url: "/MobileAL.xml" }] },
      { id: "ind-monroela-xml", name: "Monroe LA", types: [{ id: "14d-std", label: "14d Standard", url: "/MonroeLA.xml" }] },
      { id: "ind-montereyca-spectrum-xml", name: "Monterey CA-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/MontereyCA-Spectrum.xml" }] },
      { id: "ind-montereyca-xml", name: "Monterey CA", types: [{ id: "14d-std", label: "14d Standard", url: "/MontereyCA.xml" }] },
      { id: "ind-montgomery-selmaal-xml", name: "Montgomery-Selma AL", types: [{ id: "14d-std", label: "14d Standard", url: "/Montgomery-SelmaAL.xml" }] },
      { id: "ind-myrtlebeachsc-xml", name: "Myrtle Beach SC", types: [{ id: "14d-std", label: "14d Standard", url: "/MyrtleBeachSC.xml" }] },
      { id: "ind-nashvilletn-xfinity-xml", name: "Nashville TN-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/NashvilleTN-Xfinity.xml" }] },
      { id: "ind-nashvilletn-xml", name: "Nashville TN", types: [{ id: "14d-std", label: "14d Standard", url: "/NashvilleTN.xml" }] },
      { id: "ind-neworleansla-xml", name: "New Orleans LA", types: [{ id: "14d-std", label: "14d Standard", url: "/NewOrleansLA.xml" }] },
      { id: "ind-newyorkny-directv-xml", name: "New York NY-Directv", types: [{ id: "14d-std", label: "14d Standard", url: "/NewYorkNY-Directv.xml" }] },
      { id: "ind-newyorkny-fios-xml", name: "New York NY-Fios", types: [{ id: "14d-std", label: "14d Standard", url: "/NewYorkNY-Fios.xml" }] },
      { id: "ind-norfolkva-xml", name: "Norfolk VA", types: [{ id: "14d-std", label: "14d Standard", url: "/NorfolkVA.xml" }] },
      { id: "ind-northplattene-dish-xml", name: "North Platte NE-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/NorthPlatteNE-Dish.xml" }] },
      { id: "ind-nwmontana-spectrum-xml", name: "NWMontana-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/NWMontana-Spectrum.xml" }] },
      { id: "ind-odessatx-xml", name: "Odessa TX", types: [{ id: "14d-std", label: "14d Standard", url: "/OdessaTX.xml" }] },
      { id: "ind-oklahomacityok-cox-xml", name: "Oklahoma City OK-Cox", types: [{ id: "14d-std", label: "14d Standard", url: "/OklahomaCityOK-Cox.xml" }] },
      { id: "ind-oklahomacityok-xml", name: "Oklahoma City OK", types: [{ id: "14d-std", label: "14d Standard", url: "/OklahomaCityOK.xml" }] },
      { id: "ind-omahane-xml", name: "Omaha NE", types: [{ id: "14d-std", label: "14d Standard", url: "/OmahaNE.xml" }] },
      { id: "ind-orlandofl-xml", name: "Orlando FL", types: [{ id: "14d-std", label: "14d Standard", url: "/OrlandoFL.xml" }] },
      { id: "ind-ottumwaia-dish-xml", name: "Ottumwa IA-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/OttumwaIA-Dish.xml" }] },
      { id: "ind-paducahky-capegiradeaumo-xml", name: "Paducah KY-Cape Giradeau MO", types: [{ id: "14d-std", label: "14d Standard", url: "/PaducahKY-CapeGiradeauMO.xml" }] },
      { id: "ind-palmspringsca-xml", name: "Palm Springs CA", types: [{ id: "14d-std", label: "14d Standard", url: "/PalmSpringsCA.xml" }] },
      { id: "ind-panamacityfl-xml", name: "Panama City FL", types: [{ id: "14d-std", label: "14d Standard", url: "/PanamaCityFL.xml" }] },
      { id: "ind-parkersburgwv-xml", name: "Parkersburg WV", types: [{ id: "14d-std", label: "14d Standard", url: "/ParkersburgWV.xml" }] },
      { id: "ind-peoriail-xml", name: "Peoria IL", types: [{ id: "14d-std", label: "14d Standard", url: "/PeoriaIL.xml" }] },
      { id: "ind-philadelphiapa-xml", name: "Philadelphia PA", types: [{ id: "14d-std", label: "14d Standard", url: "/PhiladelphiaPA.xml" }] },
      { id: "ind-philladelphiapa-xfinity-xml", name: "Philladelphia PA-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/PhilladelphiaPA-Xfinity.xml" }] },
      { id: "ind-phoenixaz-xml", name: "Phoenix AZ", types: [{ id: "14d-std", label: "14d Standard", url: "/PhoenixAZ.xml" }] },
      { id: "ind-pittsburghpa-xml", name: "Pittsburgh PA", types: [{ id: "14d-std", label: "14d Standard", url: "/PittsburghPA.xml" }] },
      { id: "ind-portland-auburnme-xml", name: "Portland-Auburn ME", types: [{ id: "14d-std", label: "14d Standard", url: "/Portland-AuburnME.xml" }] },
      { id: "ind-portlandor-xml", name: "Portland OR", types: [{ id: "14d-std", label: "14d Standard", url: "/PortlandOR.xml" }] },
      { id: "ind-presqueisleme-dish-xml", name: "Presque Isle ME-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/PresqueIsleME-Dish.xml" }] },
      { id: "ind-providenceri-cox-xml", name: "Providence RI-Cox", types: [{ id: "14d-std", label: "14d Standard", url: "/ProvidenceRI-Cox.xml" }] },
      { id: "ind-providenceri-xml", name: "Providence RI", types: [{ id: "14d-std", label: "14d Standard", url: "/ProvidenceRI.xml" }] },
      { id: "ind-quincyil-hannibalmo-keokukia-xml", name: "Quincy IL-Hannibal MO-Keokuk IA", types: [{ id: "14d-std", label: "14d Standard", url: "/QuincyIL-HannibalMO-KeokukIA.xml" }] },
      { id: "ind-raleighnc-xml", name: "Raleigh NC", types: [{ id: "14d-std", label: "14d Standard", url: "/RaleighNC.xml" }] },
      { id: "ind-rapidcitysd-xml", name: "Rapid City SD", types: [{ id: "14d-std", label: "14d Standard", url: "/RapidCitySD.xml" }] },
      { id: "ind-renonv-xml", name: "Reno NV", types: [{ id: "14d-std", label: "14d Standard", url: "/RenoNV.xml" }] },
      { id: "ind-richmondva-xml", name: "Richmond VA", types: [{ id: "14d-std", label: "14d Standard", url: "/RichmondVA.xml" }] },
      { id: "ind-roanokeva-xml", name: "Roanoke VA", types: [{ id: "14d-std", label: "14d Standard", url: "/RoanokeVA.xml" }] },
      { id: "ind-rochestermn-xml", name: "Rochester MN", types: [{ id: "14d-std", label: "14d Standard", url: "/RochesterMN.xml" }] },
      { id: "ind-rochesterny-xml", name: "Rochester NY", types: [{ id: "14d-std", label: "14d Standard", url: "/RochesterNY.xml" }] },
      { id: "ind-rockfordil-xfinity-xml", name: "Rockford IL-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/RockfordIL-Xfinity.xml" }] },
      { id: "ind-rockfordil-xml", name: "Rockford IL", types: [{ id: "14d-std", label: "14d Standard", url: "/RockfordIL.xml" }] },
      { id: "ind-sacramentoca-uverse-xml", name: "Sacramento CA-Uverse", types: [{ id: "14d-std", label: "14d Standard", url: "/SacramentoCA-Uverse.xml" }] },
      { id: "ind-sacramentoca-xml", name: "Sacramento CA", types: [{ id: "14d-std", label: "14d Standard", url: "/SacramentoCA.xml" }] },
      { id: "ind-saintlouismo-ota-xml", name: "Saint Louis MO-OTA", types: [{ id: "14d-std", label: "14d Standard", url: "/SaintLouisMO-OTA.xml" }] },
      { id: "ind-saintlouismo-xml", name: "Saint Louis MO", types: [{ id: "14d-std", label: "14d Standard", url: "/SaintLouisMO.xml" }] },
      { id: "ind-salisburymd-xml", name: "Salisbury MD", types: [{ id: "14d-std", label: "14d Standard", url: "/SalisburyMD.xml" }] },
      { id: "ind-saltlakecityut-xml", name: "Salt Lake City UT", types: [{ id: "14d-std", label: "14d Standard", url: "/SaltLakeCityUT.xml" }] },
      { id: "ind-sanangelotx-dish-xml", name: "San Angelo TX-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/SanAngeloTX-Dish.xml" }] },
      { id: "ind-sanantoniotx-xml", name: "San Antonio TX", types: [{ id: "14d-std", label: "14d Standard", url: "/SanAntonioTX.xml" }] },
      { id: "ind-sandiegoca-cox-xml", name: "San Diego CA-Cox", types: [{ id: "14d-std", label: "14d Standard", url: "/SanDiegoCA-Cox.xml" }] },
      { id: "ind-sandiegoca-xml", name: "San Diego CA", types: [{ id: "14d-std", label: "14d Standard", url: "/SanDiegoCA.xml" }] },
      { id: "ind-sanfranciscoca-xml", name: "San Francisco CA", types: [{ id: "14d-std", label: "14d Standard", url: "/SanFranciscoCA.xml" }] },
      { id: "ind-santabarbaraca-xml", name: "Santa Barbara CA", types: [{ id: "14d-std", label: "14d Standard", url: "/SantaBarbaraCA.xml" }] },
      { id: "ind-savannahga-xml", name: "Savannah GA", types: [{ id: "14d-std", label: "14d Standard", url: "/SavannahGA.xml" }] },
      { id: "ind-seattlewa-xfinity-xml", name: "Seattle WA-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/SeattleWA-Xfinity.xml" }] },
      { id: "ind-seattlewa-xml", name: "Seattle WA", types: [{ id: "14d-std", label: "14d Standard", url: "/SeattleWA.xml" }] },
      { id: "ind-shermantx-adaok-xml", name: "Sherman TX-Ada OK", types: [{ id: "14d-std", label: "14d Standard", url: "/ShermanTX-AdaOK.xml" }] },
      { id: "ind-shreveportla-xfinity-xml", name: "Shreveport LA-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/ShreveportLA-Xfinity.xml" }] },
      { id: "ind-shreveportla-xml", name: "Shreveport LA", types: [{ id: "14d-std", label: "14d Standard", url: "/ShreveportLA.xml" }] },
      { id: "ind-siouxcityia-xml", name: "Sioux City IA", types: [{ id: "14d-std", label: "14d Standard", url: "/SiouxCityIA.xml" }] },
      { id: "ind-siouxfallssd-xml", name: "Sioux Falls SD", types: [{ id: "14d-std", label: "14d Standard", url: "/SiouxFallsSD.xml" }] },
      { id: "ind-southbendin-xml", name: "South Bend IN", types: [{ id: "14d-std", label: "14d Standard", url: "/SouthBendIN.xml" }] },
      { id: "ind-spokanewa-xml", name: "Spokane WA", types: [{ id: "14d-std", label: "14d Standard", url: "/SpokaneWA.xml" }] },
      { id: "ind-springfield-holyokema-xml", name: "Springfield-Holyoke MA", types: [{ id: "14d-std", label: "14d Standard", url: "/Springfield-HolyokeMA.xml" }] },
      { id: "ind-springfieldil-xfinity-xml", name: "Springfield IL-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/SpringfieldIL-Xfinity.xml" }] },
      { id: "ind-springfieldma-xfinity-xml", name: "Springfield MA-Xfinity", types: [{ id: "14d-std", label: "14d Standard", url: "/SpringfieldMA-Xfinity.xml" }] },
      { id: "ind-springfieldmo-uverse-xml", name: "Springfield MO-Uverse", types: [{ id: "14d-std", label: "14d Standard", url: "/SpringfieldMO-Uverse.xml" }] },
      { id: "ind-springfieldmo-xml", name: "Springfield MO", types: [{ id: "14d-std", label: "14d Standard", url: "/SpringfieldMO.xml" }] },
      { id: "ind-stjoesephmo-optimum-xml", name: "St Joeseph MO-Optimum", types: [{ id: "14d-std", label: "14d Standard", url: "/StJoesephMO-Optimum.xml" }] },
      { id: "ind-stjosephmo-xml", name: "St Joseph MO", types: [{ id: "14d-std", label: "14d Standard", url: "/StJosephMO.xml" }] },
      { id: "ind-syracuseny-xml", name: "Syracuse NY", types: [{ id: "14d-std", label: "14d Standard", url: "/SyracuseNY.xml" }] },
      { id: "ind-tallahasseefl-xml", name: "Tallahassee FL", types: [{ id: "14d-std", label: "14d Standard", url: "/TallahasseeFL.xml" }] },
      { id: "ind-tampafl-xml", name: "Tampa FL", types: [{ id: "14d-std", label: "14d Standard", url: "/TampaFL.xml" }] },
      { id: "ind-terrehautein-dish-xml", name: "Terre Haute IN-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/TerreHauteIN-Dish.xml" }] },
      { id: "ind-terrehautein-xml", name: "Terre Haute IN", types: [{ id: "14d-std", label: "14d Standard", url: "/TerreHauteIN.xml" }] },
      { id: "ind-toledooh-xml", name: "Toledo OH", types: [{ id: "14d-std", label: "14d Standard", url: "/ToledoOH.xml" }] },
      { id: "ind-topekaks-xml", name: "Topeka KS", types: [{ id: "14d-std", label: "14d Standard", url: "/TopekaKS.xml" }] },
      { id: "ind-traversecitymi-xml", name: "Traverse City MI", types: [{ id: "14d-std", label: "14d Standard", url: "/TraverseCityMI.xml" }] },
      { id: "ind-tri-citiesva-xml", name: "Tri-Cities VA", types: [{ id: "14d-std", label: "14d Standard", url: "/Tri-CitiesVA.xml" }] },
      { id: "ind-tucsonaz-xml", name: "Tucson AZ", types: [{ id: "14d-std", label: "14d Standard", url: "/TucsonAZ.xml" }] },
      { id: "ind-tulsaok-uverse-xml", name: "Tulsa OK-Uverse", types: [{ id: "14d-std", label: "14d Standard", url: "/TulsaOK-Uverse.xml" }] },
      { id: "ind-tulsaok-xml", name: "Tulsa OK", types: [{ id: "14d-std", label: "14d Standard", url: "/TulsaOK.xml" }] },
      { id: "ind-tusconaz-cox-xml", name: "Tuscon AZ-Cox", types: [{ id: "14d-std", label: "14d Standard", url: "/TusconAZ-Cox.xml" }] },
      { id: "ind-twinfallsid-xml", name: "Twin Falls ID", types: [{ id: "14d-std", label: "14d Standard", url: "/TwinFallsID.xml" }] },
      { id: "ind-tyler-longviewtn-xml", name: "Tyler-Longview TN", types: [{ id: "14d-std", label: "14d Standard", url: "/Tyler-LongviewTN.xml" }] },
      { id: "ind-uticany-xml", name: "Utica NY", types: [{ id: "14d-std", label: "14d Standard", url: "/UticaNY.xml" }] },
      { id: "ind-victoriatx-dish-xml", name: "Victoria TX-Dish", types: [{ id: "14d-std", label: "14d Standard", url: "/VictoriaTX-Dish.xml" }] },
      { id: "ind-virginiabeachva-cox-xml", name: "Virginia Beach VA-Cox", types: [{ id: "14d-std", label: "14d Standard", url: "/VirginiaBeachVA-Cox.xml" }] },
      { id: "ind-wacotx-xml", name: "Waco TX", types: [{ id: "14d-std", label: "14d Standard", url: "/WacoTX.xml" }] },
      { id: "ind-washingtondc-fios-xml", name: "Washington DC-Fios", types: [{ id: "14d-std", label: "14d Standard", url: "/WashingtonDC-Fios.xml" }] },
      { id: "ind-washingtondc-xml", name: "Washington DC", types: [{ id: "14d-std", label: "14d Standard", url: "/WashingtonDC.xml" }] },
      { id: "ind-watertownny-xml", name: "Watertown NY", types: [{ id: "14d-std", label: "14d Standard", url: "/WatertownNY.xml" }] },
      { id: "ind-wausauwi-tds-xml", name: "Wausau WI-TDS", types: [{ id: "14d-std", label: "14d Standard", url: "/WausauWI-TDS.xml" }] },
      { id: "ind-wausauwi-xml", name: "Wausau WI", types: [{ id: "14d-std", label: "14d Standard", url: "/WausauWI.xml" }] },
      { id: "ind-westpalmfl-xml", name: "West Palm FL", types: [{ id: "14d-std", label: "14d Standard", url: "/WestPalmFL.xml" }] },
      { id: "ind-wheelingwv-steubenvilleoh-xml", name: "Wheeling WV-Steubenville OH", types: [{ id: "14d-std", label: "14d Standard", url: "/WheelingWV-SteubenvilleOH.xml" }] },
      { id: "ind-wichitafallstx-spectrum-xml", name: "Wichita Falls TX-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/WichitaFallsTX-Spectrum.xml" }] },
      { id: "ind-wichitafallstx-xml", name: "Wichita Falls TX", types: [{ id: "14d-std", label: "14d Standard", url: "/WichitaFallsTX.xml" }] },
      { id: "ind-wichitaks-xml", name: "Wichita KS", types: [{ id: "14d-std", label: "14d Standard", url: "/WichitaKS.xml" }] },
      { id: "ind-wilkesbarrepa-rcn-xml", name: "Wilkes Barre PA-RCN", types: [{ id: "14d-std", label: "14d Standard", url: "/WilkesBarrePA-RCN.xml" }] },
      { id: "ind-wilkesbarrepa-xml", name: "Wilkes Barre PA", types: [{ id: "14d-std", label: "14d Standard", url: "/WilkesBarrePA.xml" }] },
      { id: "ind-wilmingtonnc-xml", name: "Wilmington NC", types: [{ id: "14d-std", label: "14d Standard", url: "/WilmingtonNC.xml" }] },
      { id: "ind-yakima-pascowa-xml", name: "Yakima-Pasco WA", types: [{ id: "14d-std", label: "14d Standard", url: "/Yakima-PascoWA.xml" }] },
      { id: "ind-yakimawa-spectrum-xml", name: "Yakima WA-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/YakimaWA-Spectrum.xml" }] },
      { id: "ind-youngstownoh-xml", name: "Youngstown OH", types: [{ id: "14d-std", label: "14d Standard", url: "/YoungstownOH.xml" }] },
      { id: "ind-yumaaz-spectrum-xml", name: "Yuma AZ-Spectrum", types: [{ id: "14d-std", label: "14d Standard", url: "/YumaAZ-Spectrum.xml" }] },
      { id: "ind-yumaaz-xml", name: "Yuma AZ", types: [{ id: "14d-std", label: "14d Standard", url: "/YumaAZ.xml" }] },
      { id: "ind-zanesvilleoh-xml", name: "Zanesville OH", types: [{ id: "14d-std", label: "14d Standard", url: "/ZanesvilleOH.xml" }] },
      { id: "ind-unitedstates24-og-xml", name: "United States24-og", types: [{ id: "14d-std", label: "14d Standard", url: "/UnitedStates24-og.xml" }] },
    ],
  },
];

// Flat lookup by region id → its group + region (for resolving a selection without re-walking groups).
const REGION_INDEX = new Map<string, JesmannRegion>();
for (const g of JESMANN_CATALOG) for (const r of g.regions) REGION_INDEX.set(r.id, r);

export function jesmannRegion(regionId: string): JesmannRegion | null {
  return REGION_INDEX.get(regionId) || null;
}

// Pick a region's default download type: '7d Standard' if it offers it, else the first available by preference.
export function jesmannDefaultType(region: JesmannRegion): JesmannType | null {
  if (!region.types.length) return null;
  for (const id of DEFAULT_TYPE_ORDER) {
    const t = region.types.find((x) => x.id === id);
    if (t) return t;
  }
  return region.types[0];
}

// Resolve a region+type selection to the concrete absolute .xml URL.
export function jesmannUrl(region: JesmannRegion, type: JesmannType): string {
  return JESMANN_BASE + type.url;
}

// A stable, unique source name for the created EpgSource (so the slug id differs per region+type and a user
// can add several Jesmann guides). e.g. 'Jesmann · United States · 7d Standard'.
export function jesmannSourceName(region: JesmannRegion, type: JesmannType): string {
  return `Jesmann · ${region.name} · ${type.label}`;
}
